# Numpy array operations

Numpy significa "Numerical python" es una libreria para computación lógica, que contiene arreglos de n dimensiones, integración con c, c++ y más.


Operaciones en arreglos de numpy

In [3]:
import numpy as np 

In [6]:
arr1 = np.arange(4, dtype = np.float64).reshape(2,2)

print("arr1")
print(arr1)

print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)
 
print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))
 
print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))
 
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
 
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))

arr1
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


In [ ]:
# np.reciprocal(arr) devuelve el reciproco de los numeros del arreglo
# np.power(arr,x) eleva cada miembro del arreglo a x
# np.power(arr,arr2) eleva a los miembros del arreglo 1 a su equivalente del arreglo 2
# np.mod(arr, arr2) funciona de manera similar, pero aplicando el modulo